version: "3"

services:
  server:
    build: ./Go
    container_name: server
    tty: true
    volumes:
      - ./Go/app/:/app
    ports:
      - 9000:9000

  front:
    build: ./node
    container_name:  front
    tty:  true
    volumes: 
      - ./node/app:/app
    networks:
      - go-node
    ports:
      - 3000:3000

networks:
  go-node:
    driver: bridge
