version: "3.9"

services:
  server:
    build: ./Go
    container_name: server
    tty: true
    volumes:
      - ./Go/app/:/app
    ports:
      - 9000:9000
    networks:
      go-node:
        ipv4_address: 192.168.1.101

      

  front:
    build: ./node
    container_name:  front
    tty:  true
    volumes: 
      - ./node/app:/app
    ports:
      - 3000:3000
    
    networks:
      go-node:
        ipv4_address: 192.168.1.102


networks:
  go-node:
    ipam:
      
      driver: default
      config:
        - subnet: 192.168.1.0/24
