version: "3"

services:
  server:
    build: ./Go
    container_name: server
    tty: true
<<<<<<< HEAD
    volumes: 
      - ./Go/app:/app
    networks: 
      - go-node
=======
    volumes:
      - ./Go/app/:/app
>>>>>>> 02b911826e7b06f86d5d79fe0bacaf61018080a1
    ports:
      - 9000:9000

  front:
    build: ./node
    container_name:  front
    tty:  true
<<<<<<< HEAD
    volumes: 
      - ./node/app:/app
    networks:
      - go-node
    ports:
      - 3000:3000

networks:
  go-node:
    driver: bridge
=======
    volumes:
      - ./node/app/:/app
>>>>>>> 02b911826e7b06f86d5d79fe0bacaf61018080a1
